export const APP_STATUS = {
  ACTIVE: "ACTIVE",
  DISABLED: "DISABLED"
};

export const LICENSE_STATUS = {
  ACTIVE: "ACTIVE",
  DISABLED: "DISABLED",
  REVOKED: "REVOKED"
};

export const DENY_REASON = {
  APP_DISABLED: "APP_DISABLED",
  LICENSE_NOT_FOUND: "LICENSE_NOT_FOUND",
  LICENSE_REVOKED: "LICENSE_REVOKED",
  LICENSE_DISABLED: "LICENSE_DISABLED",
  LICENSE_EXPIRED: "LICENSE_EXPIRED",
  MACHINE_MISMATCH: "MACHINE_MISMATCH"
};
export const SERVER_ID = process.env.SERVER_ID || "UNKNOWN";
